#!/bin/bash

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export MAVEN_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.3.9
export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
mvn package -DskipTests=true