#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export MAVEN_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.3.9
export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR

mvn package -DskipTests=true |& /usr/bin/logshifter -tag diy

nohup java -jar target/*.jar --spring.profiles.active=openshift --server.port=$OPENSHIFT_DIY_PORT --server.address=$OPENSHIFT_DIY_IP |& /usr/bin/logshifter -tag diy &